(function(){
 'use strict';
 const F=window.FinanceCore,B='finance-documents',VERSION='2026-09-v1';
 let rows=[],docs=[],closures=[],settings=null,owner=null,selectedFile=null,previewUrl=null,busy=false,ocrWorker=null,ocrPromise=null,tab='income';
 const el=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS'}).format(Number(n)||0),today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),month=()=>today().slice(0,7);
 const date=s=>s?new Date(String(s).slice(0,10)+'T12:00:00').toLocaleDateString('he-IL'):'לא צוין',expiry=d=>new Date(new Date(d.expires_at).getTime()-1).toLocaleDateString('he-IL',{timeZone:'Asia/Jerusalem'});
 function error(message,id='financeError'){const e=el(id);e.textContent=message||'';e.classList.toggle('hidden',!message);}
 function userStill(id){return state.user?.id===id;}
 async function all(table){const uid=owner;let out=[];for(let from=0;;from+=500){const r=await db.from(table).select('*').eq('professional_id',uid).order('id').range(from,from+499);if(r.error)throw r.error;out.push(...r.data);if(r.data.length<500)break;}return out;}
 async function reload(){const uid=state.user?.id;if(!uid)throw Error('יש להתחבר מחדש');owner=uid;const [a,b,c,d]=await Promise.all([all('finance_entries'),all('finance_documents'),db.from('finance_settings').select('*').eq('professional_id',uid).maybeSingle(),all('finance_closures')]);if(!userStill(uid))throw Error('החשבון השתנה');if(c.error)throw c.error;rows=a;docs=b;closures=d;settings=c.data||{business_type:'unknown',quota_bytes:104857600,advance_rate:null,reporting_months:1};}
 async function open(){if(!state.user)return;show('#financeView');error('');try{await reload();el('financeSettings').open=settings.business_type==='unknown'||settings.advance_rate===null||settings.advance_rate===undefined;render();}catch(e){error('לא ניתן לטעון את הכספים: '+friendly(e));}}
 function friendly(e){const m=String(e?.message||e||'');const map={'Period closed':'התקופה סגורה. הוסיפו מסמך תיקון בחודש פתוח.','Period already closed':'התקופה כבר סגורה.','Review pending':'יש מסמכים שממתינים לבדיקה. אשרו אותם לפני הסגירה.','Document required':'יש לצרף מסמך לפני האישור.','Complete document':'יש להשלים ספק או לקוח, תאריך וסכום.','Credit requires':'לזיכוי יש לבחור את ההכנסה המקורית וללחוץ על הוספת זיכוי.','Use linked credit':'להכנסה שאושרה מוסיפים מסמך זיכוי מקושר.','quota':'האחסון מלא. לא ניתן לצרף קובץ נוסף כרגע.','No approved':'אין מסמכים מאושרים לסגירה.','Uploads pending':'יש העלאה שטרם הסתיימה. יש להשלים אותה לפני הסגירה.'};for(const [k,v] of Object.entries(map))if(m.includes(k))return v;if(e?.code==='23505')return 'המסמך כבר קיים. חפשו אותו לפני הוספה נוספת.';if(e?.code==='PGRST116')return 'הרישום השתנה. חזרו ורעננו לפני ניסיון נוסף.';return m.slice(0,220);}
 function closed(r){return closures.find(c=>r.report_month>=c.start_month&&r.report_month<c.end_month);}
 function activeClosure(){const m=el('financeMonth').value+'-01';return closures.find(c=>m>=c.start_month&&m<c.end_month);}
 function periodData(){const c=activeClosure(),cfg=c?.snapshot.settings||settings,start=c?c.start_month.slice(0,7):el('financeMonth').value,range=F.range(start,cfg.reporting_months||1);return {c,cfg,start,range,entries:c?c.snapshot.entries:rows.filter(r=>r.report_month>=range.start&&r.report_month<range.end&&!r.voided&&!r.deletion_pending),documents:c?c.snapshot.documents:docs};}
 function visible(){const {range}=periodData(),filter=el('financeFilter').value,q=el('financeSearch').value.trim().toLowerCase();return rows.filter(r=>!r.voided&&!r.deletion_pending&&r.kind===tab&&(filter==='history'||filter==='review'?(filter==='history'||r.review_required):r.report_month>=range.start&&r.report_month<range.end)&&(!q||[r.counterparty,r.document_number,r.amount].some(x=>String(x||'').toLowerCase().includes(q)))).sort((a,b)=>String(b.document_date||b.created_at).localeCompare(String(a.document_date||a.created_at)));}
 function render(){if(!settings)return;const p=periodData(),s=F.workflowSummary(p.entries,p.start,p.cfg),card=(title,value)=>`<div class="card"><small>${title}</small><strong>${value===null?'טרם הוגדר':fmt(value)}</strong></div>`;
  document.querySelectorAll('[data-finance-tab]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.financeTab===tab));});
  el('financeRecordsPanel').classList.toggle('hidden',tab==='summary');el('financeSummaryPanel').classList.toggle('hidden',tab!=='summary');
  el('financePeriodLabel').textContent=`תקופה: ${date(p.range.start)} עד ${date(new Date(new Date(p.range.end+'T12:00:00Z')-86400000).toISOString().slice(0,10))}`;
  el('financeClosureStatus').classList.toggle('hidden',!p.c);el('financeClosureStatus').textContent=p.c?'התקופה נסגרה. ניתן להוריד את העותק הקבוע; תיקונים מוסיפים בתקופה פתוחה.':'';
  el('financeClose').disabled=!!p.c;el('financeClose').textContent=p.c?'התקופה סגורה':'סגירת התקופה והכנת החומר למסירה';
  el('financeRecordsTitle').textContent=tab==='income'?'הכנסות':'הוצאות';el('financeAdd').textContent=tab==='income'?'📷 הוספת מסמך הכנסה':'📷 הוספת מסמך הוצאה';
  el('financeRecordsHelp').textContent=tab==='income'?'מצרפים מסמך, בודקים ומאשרים. תשלום מתיק עבודה ממתין כאן לצירוף המסמך שלו.':'מצרפים מסמך ומאשרים. בתקופה פתוחה אפשר למחוק הוצאה ואת המסמך שלה.';
  el('financeSummary').innerHTML=card('כסף שהתקבל בפועל',s.income)+card('הוצאות ששולמו',s.expense)+card('הכנסות שטרם שולמו',s.unpaid)+card('הפרש לאחר תשלומי המס שתועדו',s.balance)+card('אומדן מע״מ שנותר לשמירה',s.vat)+card('אומדן מקדמה שנותרה לתשלום',s.advanceRemaining)+card('סך משוער לשמירה בצד',s.reserve);
  el('financeCalculation').innerHTML=`<p>החישוב לפי חודש השיוך של המסמכים שאושרו, כולל מסמכים שטרם שולמו.</p><p>מע״מ הכנסות: ${fmt(s.outputVat)}<br>מע״מ הוצאות שנכלל: ${fmt(s.inputVat)}<br>תשלומי מע״מ שתועדו: ${fmt(s.vatPaid)}</p><p>מחזור ללא מע״מ: ${fmt(s.turnover)}<br>מקדמות: ${p.cfg.advance_rate===null||p.cfg.advance_rate===undefined?'לא הוגדרו':esc(p.cfg.advance_rate)+'%'}<br>מס שנוכה במקור: ${fmt(s.withholding)}<br>מקדמות ששולמו: ${fmt(s.advancePaid)}</p>${s.advanceBalance<0?'<p>הניכויים והתשלומים עולים על האומדן. לא מוצג החזר אוטומטי.</p>':''}`;
  const pending=rows.filter(r=>!r.voided&&!r.deletion_pending&&r.review_required).length;
  el('financeReview').classList.toggle('hidden',!pending);el('financeReview').textContent=`${pending} מסמכים או תשלומים ממתינים לבדיקה ואינם נכללים בסיכומים. בחרו ״ממתינים לבדיקה״ בהכנסות או בהוצאות.`;
  const due=docs.filter(d=>d.status==='stored'&&new Date(d.expires_at)-Date.now()<60*86400000);el('financeExpiry').classList.toggle('hidden',!due.length);el('financeExpiry').textContent=`${due.length} מסמכים מתקרבים למחיקה. הורידו עותק עם המסמכים.`;
  const missing=[];if(settings.business_type==='unknown')missing.push('סוג העסק');if(settings.advance_rate===null||settings.advance_rate===undefined)missing.push('אחוז מקדמות מס הכנסה');
  el('financeSetupStatus').textContent=missing.length?'כדי להשלים את האומדנים, הגדירו: '+missing.join(' ו')+'.':'הגדרות החישוב: '+(settings.business_type==='exempt'?'עוסק פטור':'עסק המדווח מע״מ')+' · מקדמות '+settings.advance_rate+'% · סיכום '+(settings.reporting_months===2?'דו־חודשי':'חודשי')+'. לשינוי פתחו את ההגדרות שמתחת.';
  el('financeBusinessType').value=settings.business_type;el('financeAdvanceRate').value=settings.advance_rate??'';el('financeReportingMonths').value=settings.reporting_months||1;
  el('financeRetentionAccept').checked=settings.retention_version===VERSION&&!!settings.retention_accepted_at;
  el('financeUsage').textContent=`אחסון: ${(docs.filter(d=>['stored','pending'].includes(d.status)).reduce((n,d)=>n+Number(d.byte_size),0)/1048576).toFixed(1)} מתוך ${(settings.quota_bytes/1048576).toFixed(0)} מ״ב.`;
  el('financeList').innerHTML=visible().map(r=>`<article class="card finance-record"><div class="finance-record-top"><h3>${esc(r.counterparty||'מסמך ממתין לבדיקה')}</h3><strong>${r.amount===null?'סכום להשלמה':fmt(r.amount)}</strong></div><p>${r.review_required?'⏳ ממתין לבדיקה':closed(r)?'🔒 נכלל בתקופה סגורה':'✓ נכלל בסיכום'} · ${date(r.document_date)}${r.document_number?' · '+esc(r.document_number):''}</p><p>${r.paid_on?'תשלום: '+date(r.paid_on):'טרם שולם'}${r.withholding?' · נוכה מס: '+fmt(r.withholding):''}${r.correction_of?' · מסמך תיקון מקושר':''}</p><button class="secondary" type="button" data-finance-edit="${r.id}">${closed(r)?'צפייה במסמך ובפרטים':'פתיחה / השלמת פרטים'}</button>${r.kind==='expense'&&!closed(r)?`<button class="ghost" type="button" data-finance-delete="${r.id}">מחיקת ההוצאה</button>`:''}</article>`).join('')||'<div class="card"><p>אין מסמכים בתצוגה זו. אפשר להוסיף מסמך או לבחור תקופה אחרת.</p></div>';
  el('financeList').querySelectorAll('[data-finance-edit]').forEach(b=>b.onclick=()=>edit(rows.find(r=>r.id===b.dataset.financeEdit)));el('financeList').querySelectorAll('[data-finance-delete]').forEach(b=>b.onclick=()=>removeEntry(b.dataset.financeDelete));
  el('financeExportParts').replaceChildren();
 }
 function clearFile(){selectedFile=null;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null;el('financePreview').removeAttribute('src');el('financePreview').classList.add('hidden');el('financeScan').classList.add('hidden');el('financeRemoveFile').classList.add('hidden');el('financeFileStatus').textContent='';el('financeFile').value='';el('financeCamera').value='';}
 async function edit(r,kind='expense',correction=null){if(busy)return;if(!r&&!requireServiceAccess())return;clearFile();el('financeForm').reset();error('','financeFormError');
  el('financeForm').querySelectorAll('input,select,textarea,button').forEach(x=>{x.disabled=false;if('readOnly'in x)x.readOnly=false;});
  el('financeEntryId').value=r?.id||'';el('financeCorrection').value=r?.correction_of||correction?.id||'';el('financeEntryTitle').textContent=correction?'מסמך זיכוי / תיקון':r?'פרטי המסמך':kind==='income'?'מסמך הכנסה חדש':'מסמך הוצאה חדש';
  const map={financeKind:r?.kind||kind,financeCounterparty:r?.counterparty||correction?.counterparty||'',financeAmount:r?.amount??'',financeNumber:r?.document_number||'',financeDocDate:r?.document_date||'',financePaidDate:r?.paid_on||today(),financeCategory:r?.category||'other',financeVat:r?.vat_amount??'',financeDeductible:r?.deductible_vat??0,financeVatMonth:(r?.report_month||el('financeMonth').value).slice(0,7),financeNotes:r?.notes||'',financeWithholding:r?.withholding||0};
  if(correction){let m=month();while(closures.some(c=>m+'-01'>=c.start_month&&m+'-01'<c.end_month))m=F.range(m).end.slice(0,7);map.financeVatMonth=m;}
  for(const [id,v] of Object.entries(map))el(id).value=v;
  el('financeKind').disabled=!!r||!!correction;el('financePaid').checked=!!r?.paid_on;el('financeVerified').checked=false;
  const source=!!r&&r.source!=='manual',locked=!!r&&!!closed(r),approvedIncome=r?.kind==='income'&&!!r.approved_at;
  el('financeAmount').readOnly=source||approvedIncome;for(const id of ['financeCounterparty','financeNumber','financeVat'])el(id).readOnly=approvedIncome;
  el('financeSourceNote').classList.toggle('hidden',!source&&!locked&&!approvedIncome&&!correction);el('financeSourceNote').textContent=locked?'התקופה סגורה. הפרטים נשמרים כפי שנמסרו.':correction?'צרפו מסמך זיכוי והזינו את הסכומים בסימן שלילי.':approvedIncome?'ההכנסה אושרה. לביטול או החזר הוסיפו מסמך זיכוי מקושר.':source?'התשלום הגיע מתיק עבודה. צרפו מסמך ואשרו את הפרטים. הסכום מנוהל בתיק העבודה.':'';
  el('financeVoid').classList.toggle('hidden',!r||r.kind!=='expense'||locked);el('financeCredit').classList.toggle('hidden',!r||r.kind!=='income');el('financeCredit').onclick=()=>edit(null,'income',r);
  el('financeSave').classList.toggle('hidden',locked);el('financeDraft').classList.toggle('hidden',locked||!!r?.approved_at);
  el('financeJob').innerHTML='<option value="">הוצאה כללית</option>';show('#financeEntryView');updateFields();renderDocs(r?.id);
  if(locked){el('financeForm').querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);for(const id of ['financeCameraBtn','financeFileBtn'])el(id).disabled=true;}
  const uid=state.user.id;await loadProJobs();if(!userStill(uid))return;el('financeJob').innerHTML+=state.proJobs.map(j=>`<option value="${j.id}">${esc(j.customer_name)} — ${esc(j.description).slice(0,60)}</option>`).join('');el('financeJob').value=r?.job_id||'';
 }
 function updateFields(){const income=el('financeKind').value==='income';el('financeDeductibleLabel').classList.toggle('hidden',income);el('financeWithholdingLabel').classList.toggle('hidden',!income);el('financeJobLabel').classList.toggle('hidden',income);el('financePaidDateLabel').classList.toggle('hidden',!el('financePaid').checked);el('financeUploadPolicy').textContent=settings?.retention_version===VERSION?'צילום ברור או קובץ PDF. אם הזיהוי לא הצליח אפשר להשלים ידנית.':'באישור הצירוף תתבקשו לאשר את משך שמירת המסמכים.';el('financeNetPayment').textContent=income&&el('financePaid').checked?'יתקבל בפועל לאחר הניכוי: '+fmt(F.amount(el('financeAmount').value)-F.amount(el('financeWithholding').value||0)):'';}
 function renderDocs(entryId){const list=docs.filter(d=>d.entry_id===entryId);el('financeExistingDocs').innerHTML=list.map(d=>`<div class="finance-doc"><b>${esc(d.original_name)}</b><p>${d.status==='stored'?`מחיקה אוטומטית בתום ${expiry(d)}`:d.status==='expired'?'הקובץ נמחק לפי מדיניות השמירה; הנתונים נשמרו.':d.status==='pending'?'העלאה לא הושלמה; יש לרענן או לנסות שוב מאוחר יותר.':'ההעלאה לא הושלמה והקובץ פונה.'}</p>${d.status==='stored'?`<button class="secondary" type="button" data-finance-doc="${d.id}">הצג / הורד מסמך</button>`:d.status==='pending'?`<button class="secondary" type="button" data-finance-complete="${d.id}">בדיקה והשלמת שמירה</button>`:''}</div>`).join('');el('financeExistingDocs').querySelectorAll('[data-finance-complete]').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await db.from('finance_documents').update({status:'stored'}).eq('id',b.dataset.financeComplete).select('*').single();if(r.error){toast('הקובץ עדיין לא הועלה במלואו. הזמנת ההעלאה תתפנה בתוך יום ואפשר יהיה לנסות שוב.');b.disabled=false;return;}docs=docs.map(d=>d.id===r.data.id?r.data:d);clearFile();renderDocs(entryId);});el('financeExistingDocs').querySelectorAll('[data-finance-doc]').forEach(b=>b.onclick=()=>downloadDoc(docs.find(d=>d.id===b.dataset.financeDoc),b));}
 function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
 async function downloadDoc(d,b){b.disabled=true;try{const r=await db.storage.from(B).download(d.storage_path);if(r.error)throw r.error;download(r.data,d.original_name);}catch(e){toast('המסמך לא הורד: '+friendly(e));}finally{b.disabled=false;}}
 async function prepareFile(file){if(busy||!file)return;if(settings?.retention_version!==VERSION||!settings?.retention_accepted_at){if(!confirm('המסמכים נשמרים עד סוף החודש שלאחר השלמת שנה מההעלאה. לאחר מכן יימחקו אוטומטית. יש לשמור עותק מחוץ למחירלי. לאשר?'))return;el('financeRetentionAccept').checked=true;if(!await settingsSave(true))return;}
  if(file.size>20*1048576){toast('התמונה גדולה מדי. בחרו קובץ עד 20 מ״ב');return;}busy=true;el('financeSave').disabled=true;clearFile();
  try{
   const sig=new Uint8Array(await file.slice(0,12).arrayBuffer());const pdf=String.fromCharCode(...sig.slice(0,5))==='%PDF-';
   const jpeg=sig[0]===255&&sig[1]===216,png=sig[0]===137&&sig[1]===80&&sig[2]===78&&sig[3]===71,webp=String.fromCharCode(...sig.slice(0,4))==='RIFF'&&String.fromCharCode(...sig.slice(8,12))==='WEBP';
   if(pdf){if(file.size>5*1048576)throw Error('קובץ PDF יכול להיות עד 5 מ״ב');selectedFile=new File([file],file.name,{type:'application/pdf'});}
   else {if(!jpeg&&!png&&!webp)throw Error('יש לבחור תמונת JPG, PNG, WEBP או קובץ PDF. בתמונת HEIC יש לייצא תחילה ל־JPG.');
    const bitmap=await createImageBitmap(file);try{
     const scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);
     const blob=await new Promise(res=>canvas.toBlob(res,'image/jpeg',.88));canvas.width=canvas.height=1;if(!blob)throw Error('לא ניתן לעבד את התמונה');if(blob.size>5*1048576)throw Error('הצילום עדיין גדול מדי. צלמו את המסמך מקרוב שוב.');selectedFile=new File([blob],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'});
    }finally{bitmap.close();}
   }
   if(selectedFile.type!=='application/pdf'){previewUrl=URL.createObjectURL(selectedFile);el('financePreview').src=previewUrl;el('financePreview').classList.remove('hidden');el('financeScan').classList.remove('hidden');}
   el('financeRemoveFile').classList.remove('hidden');el('financeFileStatus').textContent=`${selectedFile.name} · ${(selectedFile.size/1024).toFixed(0)} ק״ב. בדקו שהמסמך קריא לפני השמירה.`;
  }catch(e){error(friendly(e),'financeFormError');clearFile();}finally{busy=false;el('financeSave').disabled=false;}
  if(selectedFile?.type!=='application/pdf'&&selectedFile)await scan();
 }
 function loadOcr(){if(window.Tesseract)return Promise.resolve();if(ocrPromise)return ocrPromise;ocrPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';script.onload=resolve;script.onerror=()=>{ocrPromise=null;script.remove();reject(Error('לא ניתן לטעון זיהוי טקסט. אפשר להזין את הפרטים ידנית.'));};document.head.append(script);});return ocrPromise;}
 async function scan(){if(busy||!selectedFile||selectedFile.type==='application/pdf')return;busy=true;el('financeScan').disabled=true;el('financeSave').disabled=true;el('financeBack').disabled=true;el('financeRemoveFile').disabled=true;let timeout,cancelled=false;
  try{await loadOcr();el('financeFileStatus').textContent='טוען זיהוי עברית ואנגלית. בפעם הראשונה הפעולה עשויה להימשך כדקה…';
   const result=await Promise.race([(async()=>{const worker=await Tesseract.createWorker(['heb','eng'],1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.1',cacheMethod:'none',logger:m=>{if(m.status==='recognizing text')el('financeFileStatus').textContent=`מזהה פרטים: ${Math.round((m.progress||0)*100)}%`;}});if(cancelled){await worker.terminate();throw Error('הזיהוי בוטל');}ocrWorker=worker;return worker.recognize(selectedFile);})(),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('הזיהוי ארך יותר מדי. אפשר להקליד את הפרטים ולשמור.')),90000);})]);
   const guess=F.parseOcr(result.data.text),fields={amount:'financeAmount',vat_amount:'financeVat',document_date:'financeDocDate',document_number:'financeNumber'};let count=0;
   for(const [k,id] of Object.entries(fields))if(guess[k]!==undefined&&!el(id).readOnly){el(id).value=guess[k];count++;}
   for(const id of Object.values(fields))el(id).classList.toggle('finance-missing',!el(id).value);el('financeCounterparty').classList.toggle('finance-missing',!el('financeCounterparty').value);el('financeVerified').checked=false;if(guess.vat_amount!==undefined&&el('financeKind').value==='expense')el('financeDeductible').value=guess.vat_amount;if(guess.document_date&&!el('financeCorrection').value)el('financeVatMonth').value=guess.document_date.slice(0,7);updateFields();el('financeFileStatus').textContent=count?'הפרטים שזוהו מולאו כהצעה בלבד. בדקו ספק/לקוח, תאריך, מספר מסמך וסכומים לפני האישור.':'לא זוהו שדות בביטחון. אפשר להזין אותם ידנית; המסמך עדיין ניתן לשמירה.';
  }catch(e){el('financeFileStatus').textContent=friendly(e);}finally{cancelled=true;clearTimeout(timeout);if(ocrWorker){await ocrWorker.terminate().catch(()=>{});ocrWorker=null;}busy=false;el('financeScan').disabled=false;el('financeSave').disabled=false;el('financeBack').disabled=false;el('financeRemoveFile').disabled=false;}
 }
 async function save(event,draft=false){event?.preventDefault();if(busy||!requireServiceAccess())return;const uid=state.user.id;busy=true;el('financeSave').disabled=true;el('financeDraft').disabled=true;error('','financeFormError');let entryId=el('financeEntryId').value;
  try{const original=rows.find(r=>r.id===entryId),income=el('financeKind').value==='income';if(original&&closed(original))throw Error('Period closed');
   if(!selectedFile&&!docs.some(d=>d.entry_id===entryId&&['stored','expired'].includes(d.status)))throw Error('Document required');
   let row={kind:el('financeKind').value,amount:el('financeAmount').value===''?null:F.amount(el('financeAmount').value),counterparty:el('financeCounterparty').value.trim(),document_number:el('financeNumber').value.trim(),document_date:el('financeDocDate').value||null,paid_on:el('financePaid').checked?el('financePaidDate').value:null,category:el('financeCategory').value,notes:el('financeNotes').value.trim(),job_id:original&&original.source!=='manual'?original.job_id:income?null:el('financeJob').value||null,vat_amount:F.amount(el('financeVat').value||0),deductible_vat:income?0:F.amount(el('financeDeductible').value||0),withholding:income?F.amount(el('financeWithholding').value||0):0,report_month:el('financeVatMonth').value+'-01',vat_period:el('financeVatMonth').value+'-01',vat_confirmed:!draft,review_required:true,correction_of:el('financeCorrection').value||null};
   if(!el('financeVatMonth').value)throw Error('בחרו חודש לשיוך המסמך');
   if(row.amount!==null&&!Number.isFinite(row.amount))throw Error('סכום לא תקין');
   if(!Number.isFinite(row.withholding)||Math.abs(row.withholding)>Math.abs(row.amount||0)||(row.withholding&&Math.sign(row.withholding)!==Math.sign(row.amount)))throw Error('יש לבדוק את סכום הניכוי במקור');
   if(!draft){F.validate(row);if(!row.document_date||!row.counterparty)throw Error('Complete document details');if(!el('financeVerified').checked)throw Error('בדקו את הפרטים וסמנו את האישור');if(el('financeVat').value==='')throw Error('השלימו את המע״מ מהמסמך, או 0 אם אין מע״מ');if(el('financePaid').checked&&!row.paid_on)throw Error('השלימו תאריך תשלום');}
   let hash;if(selectedFile){hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await selectedFile.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(docs.some(d=>d.sha256===hash&&['stored','pending'].includes(d.status)))throw Error('הקובץ כבר קיים. פתחו את הרישום הקיים.');}
   if(original?.approved_at)row.review_required=false;
   let query=entryId?db.from('finance_entries').update(row).eq('id',entryId).eq('professional_id',uid):db.from('finance_entries').insert(row);if(entryId&&original?.updated_at)query=query.eq('updated_at',original.updated_at);
   const result=await query.select('*').single();if(result.error)throw result.error;entryId=result.data.id;el('financeEntryId').value=entryId;rows=rows.filter(r=>r.id!==entryId).concat(result.data);
   if(selectedFile){if(!userStill(uid))throw Error('החשבון השתנה');const reservation=await db.from('finance_documents').insert({entry_id:entryId,original_name:selectedFile.name.slice(0,200),mime_type:selectedFile.type,byte_size:selectedFile.size,sha256:hash}).select('*').single();if(reservation.error)throw reservation.error;const d=reservation.data;docs.push(d);const upload=await db.storage.from(B).upload(d.storage_path,selectedFile,{contentType:selectedFile.type,upsert:false,cacheControl:'0'});if(upload.error)throw upload.error;const complete=await db.from('finance_documents').update({status:'stored'}).eq('id',d.id).select('*').single();if(complete.error)throw complete.error;docs=docs.map(x=>x.id===d.id?complete.data:x);clearFile();}
   if(!draft){const approval=await db.from('finance_entries').update({review_required:false}).eq('id',entryId).eq('professional_id',uid).eq('updated_at',result.data.updated_at).select('*').single();if(approval.error)throw approval.error;}
   toast(draft?'המסמך נשמר וממתין לבדיקה':'המסמך אושר ונכלל בסיכום');await reload();tab=row.kind;render();show('#financeView');
  }catch(e){error(friendly(e)+(entryId?' אפשר לחזור למסמך ולהשלים את השמירה.':''),'financeFormError');renderDocs(entryId);}finally{busy=false;el('financeSave').disabled=false;el('financeDraft').disabled=false;}
 }
 async function settingsSave(accept=false){if(!requireServiceAccess())return false;const rate=el('financeAdvanceRate').value;if(rate!==''&&(!Number.isFinite(Number(rate))||Number(rate)<0||Number(rate)>100)){toast('אחוז המקדמות צריך להיות בין 0 ל־100');return false;}const row={business_type:el('financeBusinessType').value,advance_rate:rate===''?null:Number(rate),reporting_months:Number(el('financeReportingMonths').value)};if(accept){row.retention_accepted_at=new Date().toISOString();row.retention_version=VERSION;}const q=settings?.professional_id?db.from('finance_settings').update(row).eq('professional_id',state.user.id):db.from('finance_settings').insert({...row,professional_id:state.user.id});const r=await q.select('*').single();if(r.error){toast(friendly(r.error));return false;}settings=r.data;if(!accept)render();toast('ההגדרות נשמרו');return true;}
 function exportRows(list){return [['מזהה','סוג','ספק / לקוח','מספר מסמך','תאריך מסמך','תאריך תשלום','סכום כולל','מע״מ במסמך','מע״מ שנכלל','חודש שיוך','ניכוי במקור','התקבל נטו','ממתין לבדיקה','מסמך מקור לתיקון','קטגוריה','הערות'],...list.map(r=>[r.id,r.kind,r.counterparty,r.document_number,r.document_date,r.paid_on,r.amount,r.vat_amount,r.deductible_vat,r.report_month,r.withholding,r.kind==='income'&&r.paid_on?Number(r.amount)-Number(r.withholding):'',r.review_required?'כן':'לא',r.correction_of,r.category,r.notes])];}
 function exportCsv(){const p=periodData();download(new Blob([F.csv(exportRows(p.entries))],{type:'text/csv;charset=utf-8'}),'mehirli-finance-'+p.start+'.csv');}
 function exportParts(){const p=periodData(),list=p.entries,ids=new Set(list.map(r=>r.id)),documents=p.documents.filter(d=>ids.has(d.entry_id)).map(d=>({...d,status:docs.find(x=>x.id===d.id)?.status||d.status})),stored=documents.filter(d=>d.status==='stored');const batches=[[]];let bytes=0;for(const d of stored){if(bytes+Number(d.byte_size)>20*1048576){batches.push([]);bytes=0;}batches.at(-1).push(d);bytes+=Number(d.byte_size);}
  el('financeExportParts').innerHTML=`<p>הורידו את כל ${batches.length} החלקים ופתחו אותם לבדיקה. כל חלק כולל את טבלת הרישומים ורשימת המסמכים. מסמכים שכבר נמחקו אינם ניתנים לשחזור.</p>`;
  batches.forEach((batch,i)=>{const b=document.createElement('button');b.className='secondary';b.type='button';b.textContent=`הורדת ארכיון — חלק ${i+1} מתוך ${batches.length} (${batch.length} מסמכים)`;b.onclick=async()=>{
   if(busy)return;busy=true;b.disabled=true;const old=b.textContent;
   try{const files=[],enc=new TextEncoder();for(let j=0;j<batch.length;j++){b.textContent=`מוריד מסמך ${j+1} מתוך ${batch.length}…`;const d=batch[j],r=await db.storage.from(B).download(d.storage_path);if(r.error)throw Error('לא ניתן להוריד את '+d.original_name+'. הארכיון לא נוצר; נסו שוב.');files.push({name:'documents/'+d.id+d.storage_path.slice(d.storage_path.lastIndexOf('.')),data:new Uint8Array(await r.data.arrayBuffer())});}
    files.push({name:'summary.json',data:enc.encode(JSON.stringify({period:p.range,settings:p.cfg,summary:F.workflowSummary(list,p.start,p.cfg),closed_at:p.c?.created_at||null},null,2))});
    files.push({name:'entries.csv',data:enc.encode(F.csv(exportRows(list)))});
    files.push({name:'documents.csv',data:enc.encode(F.csv([['מזהה מסמך','מזהה רישום','שם מקורי','מצב','מחיקה בתום','כלול בחלק זה','נתיב בארכיון'],...documents.map(d=>[d.id,d.entry_id,d.original_name,d.status,expiry(d),batch.some(x=>x.id===d.id)?'כן':'לא','documents/'+d.id+d.storage_path.slice(d.storage_path.lastIndexOf('.'))])]))});
    files.push({name:'README.txt',data:enc.encode('ארכיון מחירלי. יש להוריד את כל החלקים, לפתוח את הקבצים ולשמור גיבוי עצמאי. CSV הוא סיכום ואינו מחליף את המסמכים. תאריך הייצוא: '+new Date().toISOString())});
    download(F.zip(files),`mehirli-archive-${el('financeMonth').value}-part-${i+1}.zip`);b.textContent='הקובץ נמסר להורדה — בדקו שנשמר ונפתח';
   }catch(e){b.textContent=old;error(friendly(e));}finally{busy=false;b.disabled=false;}
  };el('financeExportParts').append(b);});
 }
 async function closePeriod(){if(busy||!requireServiceAccess())return;const p=periodData();if(p.c)return;if(!confirm('לסגור את התקופה? לאחר הסגירה לא ניתן לשנות או למחוק את הרשומות שבה. בסיום תוכלו להוריד את החומר למסירה.'))return;busy=true;try{const r=await db.rpc('finance_close_period',{p_month:p.start+'-01'});if(r.error)throw r.error;await reload();render();exportParts();toast('התקופה נסגרה. הורידו את כל חלקי הארכיון.');}catch(e){error(friendly(e));}finally{busy=false;}}
 async function removeEntry(id){if(busy||!requireServiceAccess())return;const r=rows.find(x=>x.id===id);if(!r||r.kind!=='expense'||closed(r))return;if(!confirm('למחוק את ההוצאה ואת המסמכים המצורפים ממחירלי? לא ניתן לשחזר את המחיקה.'))return;busy=true;try{const result=await db.functions.invoke('mehirli-finance-delete',{body:{entry_id:id}});if(result.error)throw result.error;if(result.data?.error)throw Error(result.data.error);clearFile();await reload();render();show('#financeView');toast(result.data?.pending?'ההוצאה הוסרה. מחיקת הקובץ תושלם אוטומטית.':'ההוצאה והמסמכים נמחקו');}catch(e){toast('המחיקה לא הושלמה: '+friendly(e));}finally{busy=false;}}
 document.querySelectorAll('[data-finance-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.financeTab;render();});
 for(const id of ['subscriptionFinanceBtn','financeBtn','homeFinanceBtn','financeRefresh'])el(id).onclick=open;
 el('financeMonth').value=month();el('financeMonth').onchange=render;el('financeFilter').onchange=render;el('financeSearch').oninput=render;
 el('financeAdd').onclick=()=>edit(null,tab);el('financeBack').onclick=()=>{if(!busy){clearFile();render();show('#financeView');}};el('financeKind').onchange=updateFields;el('financePaid').onchange=updateFields;
 el('financeSaveSettings').onclick=()=>settingsSave();el('financeAcceptPolicy').onclick=()=>{if(el('financeRetentionAccept').checked)settingsSave(true);else toast('סמנו את אישור מדיניות השמירה');};
 el('financeCameraBtn').onclick=()=>el('financeCamera').click();el('financeFileBtn').onclick=()=>el('financeFile').click();for(const id of ['financeCamera','financeFile'])el(id).onchange=e=>prepareFile(e.target.files?.[0]);
 el('financeRemoveFile').onclick=()=>{if(!busy)clearFile();};el('financeScan').onclick=scan;el('financeForm').onsubmit=e=>save(e);el('financeDraft').onclick=()=>save(null,true);el('financeVoid').onclick=()=>removeEntry(el('financeEntryId').value);
 el('financeVat').oninput=()=>{if(el('financeKind').value==='expense')el('financeDeductible').value=el('financeVat').value;};el('financeDocDate').onchange=()=>{if(el('financeDocDate').value&&!el('financeCorrection').value)el('financeVatMonth').value=el('financeDocDate').value.slice(0,7);};el('financeWithholding').oninput=updateFields;el('financeAmount').oninput=updateFields;
 el('financeExportCsv').onclick=exportCsv;el('financeExportZip').onclick=exportParts;el('financeClose').onclick=closePeriod;
 db.auth.onAuthStateChange((event,session)=>{if(owner&&owner!==session?.user?.id){rows=[];docs=[];closures=[];settings=null;owner=null;tab='income';clearFile();for(const id of ['financeList','financeSummary','financeExistingDocs','financeExportParts','financeCalculation'])el(id).replaceChildren();el('financeForm').reset();}});
 window.MehirliFinance={open,monthIncome:async()=>{if(!state.user)return null;await reload();return F.workflowSummary(rows,month(),{...settings,reporting_months:1}).income;}};
})();
