const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const F=require('../finance-core.js');
test('cash dates, signed refunds, unpaid and unreviewed entries',()=>{const base={kind:'income',amount:100,paid_on:'2026-09-30',vat_confirmed:false};const s=F.summary([base,{...base,amount:-20},{...base,amount:900,paid_on:null},{...base,amount:500,review_required:true},{...base,amount:1000,paid_on:'2026-10-01'},{...base,kind:'expense',amount:30}], '2026-09','vat');assert.equal(s.income,80);assert.equal(s.expense,30);assert.equal(s.balance,50);assert.equal(s.review,1);});
test('only explicitly approved VAT contributes and exempt businesses show no reserve',()=>{const a=[{kind:'income',amount:118,vat_amount:18,vat_period:'2026-09-01',vat_confirmed:true},{kind:'expense',amount:59,vat_amount:9,deductible_vat:3,vat_period:'2026-09-01',vat_confirmed:true},{kind:'expense',amount:1180,vat_amount:180,deductible_vat:180,vat_period:'2026-09-01',vat_confirmed:false}];assert.equal(F.summary(a,'2026-09','vat').reserve,15);assert.equal(F.summary(a,'2026-09','exempt').reserve,null);});
test('cent precision without integer rounding',()=>{assert.equal(F.summary([{kind:'income',amount:.1,paid_on:'2026-09-01'},{kind:'income',amount:.2,paid_on:'2026-09-01'}],'2026-09','unknown').income,.3);});
test('VAT validation refuses excessive or wrong-sign deductions',()=>{assert.throws(()=>F.validate({kind:'expense',amount:118,vat_amount:18,deductible_vat:19,counterparty:''}));assert.throws(()=>F.validate({kind:'income',amount:118,vat_amount:-18,deductible_vat:0,counterparty:''}));assert.equal(F.validate({kind:'expense',amount:-118,vat_amount:-18,deductible_vat:-9,counterparty:''}).deductible_vat,-9);});
test('OCR proposals only; never use a tax percentage as the total',()=>{assert.deepEqual(F.parseOcr('חשבונית מס 12345\n25/09/2026\nמע״מ 18% 18.00\nסה״כ לתשלום 118.00'),{document_date:'2026-09-25',vat_amount:18,amount:118,document_number:'12345'});assert.equal(F.parseOcr('31/02/2026\nמע״מ 18%').document_date,undefined);});
test('CSV neutralizes spreadsheet formulas and escapes quotes',()=>{assert.ok(F.csv([['=HYPERLINK("bad")','+cmd','ספק']]).includes("'=HYPERLINK"));});
test('ZIP preserves Hebrew names and file bytes',async()=>{const zip=F.zip([{name:'מסמך.txt',data:new TextEncoder().encode('שלום')},{name:'entries.csv',data:new TextEncoder().encode('123')}]);fs.writeFileSync('/tmp/mehirli-finance-test.zip',Buffer.from(await zip.arrayBuffer()));assert.equal(new DataView(await zip.arrayBuffer()).getUint32(0,true),0x04034b50);});
